### ISSUE TITLE
unable to deserialize datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn

### ISSUE THREAD

**Issue by domparry** [ngrunwald/datasplash#12]
Hi there. I'm getting an exception trying to run the following:

If I remove the block below  ;; log the message, then it submits successfully and runs. I can see it processing pubsub messages. I was trying to write these to a BigQuery table, but getting errors. I then thought I'd try to see what the structure of the messages was, and used this bit of code from your example to try to log the messages. Am I doing something wrong or is there an issue here?

``` 
(defn apply-transformations-to-pipeline
 [read-subscription outputTable pipeline]

(->> pipeline

      ;; Read the messages from PubSub
      (ps/read-from-pubsub read-subscription {:name "read-interactions-from-pubsub"})

      ;; log the message

      (ds/map (fn [message]
                (do
                 (log/info (str "Got message:\n" message))))
              {:name "log-message"})))
```
Stacktrace below:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: unable to deserialize datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn$ff19274a@730bea0, compiling:(/private/var/folders/mc/6vrbpxbs60q4hwdrp8wm89380000gn/T/form-init1605582858210262277.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: unable to deserialize datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn$ff19274a@730bea0
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:76)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.clone(SerializableUtils.java:91)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Bound.<init>(ParDo.java:720)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Unbound.of(ParDo.java:678)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Unbound.access$000(ParDo.java:596)
	at com.google.cloud.dataflow.sdk.transforms.ParDo.of(ParDo.java:563)
	at com.google.cloud.dataflow.sdk.transforms.ParDo.of(ParDo.java:558)
	at datasplash.core$map_op$make_map_op__5352.invoke(core.clj:500)
	at fulliautomatix.core$apply_transformations_to_pipeline.invokeStatic(core.clj:33)
	at fulliautomatix.core$apply_transformations_to_pipeline.invoke(core.clj:24)
	at fulliautomatix.core$_main.invokeStatic(core.clj:89)
	at fulliautomatix.core$_main.doInvoke(core.clj:79)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init1605582858210262277.clj:1)
	at user$eval5.invoke(form-init1605582858210262277.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Caused by: java.lang.ClassNotFoundException: fulliautomatix.core$apply_transformations_to_pipeline$fn__45
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1714)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:73)
	... 32 more
```

**Comment by domparry** [comment]
I don't think it's related. Even if I resolve that dependency, I'm getting that error trying to apply any transformations. For example, if I remove that block, replace with my transform:

(ds/map (fn [[sender referenceNumber userId requestId date interactionId type payload user __key__ __error__ __has_error__]]
                  {:sender "test"
                   :referenceNumber "domtest123"
                   :userId "dom@test.com"
                   :requestId "long uuid"
                   :date "date"
                   :interactionId "notherlonguuid"
                   :type "testType"
                   :payload "{'stuff':'in a record'}"
                   :user "{'stuff':'in a record'}"
                   :__key__ "{'stuff':'in a record'}"
                   :__error__ "EhROAR"
                   :__has_error__ false})
             {:name "create-BQ-row"})

, and re-try I get:

lein run
Feb 17, 2017 5:26:02 PM com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner fromOptions
INFO: PipelineOptions.filesToStage was not specified. Defaulting to files from the classpath: will stage 88 files. Enable logging at DEBUG level to see which files will be staged.
Exception in thread "main" java.lang.IllegalArgumentException: unable to deserialize datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn$ff19274a@4aa22cc2, compiling:(/private/var/folders/mc/6vrbpxbs60q4hwdrp8wm89380000gn/T/form-init8823920201956763615.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: unable to deserialize datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn$ff19274a@4aa22cc2
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:76)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.clone(SerializableUtils.java:91)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Bound.<init>(ParDo.java:720)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Unbound.of(ParDo.java:678)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Unbound.access$000(ParDo.java:596)
	at com.google.cloud.dataflow.sdk.transforms.ParDo.of(ParDo.java:563)
	at com.google.cloud.dataflow.sdk.transforms.ParDo.of(ParDo.java:558)
	at datasplash.core$map_op$make_map_op__5352.invoke(core.clj:500)
	at fulliautomatix.core$apply_transformations_to_pipeline.invokeStatic(core.clj:38)
	at fulliautomatix.core$apply_transformations_to_pipeline.invoke(core.clj:23)
	at fulliautomatix.core$_main.invokeStatic(core.clj:81)
	at fulliautomatix.core$_main.doInvoke(core.clj:71)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init8823920201956763615.clj:1)
	at user$eval5.invoke(form-init8823920201956763615.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Caused by: java.lang.ClassNotFoundException: fulliautomatix.core$apply_transformations_to_pipeline$fn__46
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1714)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:73)
	... 32 more

**Comment by MartinSahlen** [comment]
Will check out, btw would be great if you could use markdown to format code and log outputs, it makes it more readable.

**Comment by domparry** [comment]
Thanks. Good point. Sorry about that, I have fixed above.

**Comment by MartinSahlen** [comment]
So, when you mean "fail", do you mean that it fails to write to write to bigquery? Sorry if i'm asking obvious questions, just need some clarity.

**Comment by domparry** [comment]
Sorry, I'm not being very useful here am I. Here is the stack trace from dataflow when the BQ part fails:

```
exception: "org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [map type; class com.google.api.services.bigquery.model.TableRow, [simple type, class java.lang.String] -> [simple type, class java.lang.Object]] from JSON String; no single-String constructor/factory method
	at org.codehaus.jackson.map.deser.std.StdValueInstantiator._createFromStringFallbacks(StdValueInstantiator.java:379)
	at org.codehaus.jackson.map.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:268)
	at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:244)
	at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1863)
	at datasplash.bq$clj_nested__GT_table_row.invokeStatic(bq.clj:106)
	at datasplash.bq$clj_nested__GT_table_row.invoke(bq.clj:97)
	at datasplash.core$map_fn$fn__5162.invoke(core.clj:309)
	at datasplash.core$dofn$fn__4992.invoke(core.clj:205)
	at datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn$ff19274a.processElement(Unknown Source)
	at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:49)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:139)
	at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:190)
	at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47)
	at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55)
	at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:224)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.start(ReadOperation.java:185)
	at com.google.cloud.dataflow.sdk.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:72)
	at com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:710)
	at com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker.access$500(StreamingDataflowWorker.java:99)
	at com.google.cloud.dataflow.sdk.runners.worker.StreamingDataflowWorker$8.run(StreamingDataflowWorker.java:799)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

here is the whole code block for the job:

```
(ns fulliautomatix.core
  (:require [clojure.string :as str]
            [clojure.tools.logging :as log]
            [datasplash
             [api :as ds]
             [bq :as bq]
             [pubsub :as ps]])
  (:import [java.util UUID]
           [com.google.cloud.dataflow.sdk.options DataflowPipelineOptions])
  (:gen-class))


(def pipeline-options
  {:project "simply-pre-prod"
   :job-name "streaming-events-to-bq"
   :stagingLocation (str "gs://pre-prod-dataflow-test/jars")
   :runner "DataflowPipelineRunner"
   :streaming true
   :autoscalingAlgorithm "NONE"
   :numWorkers 1
   :zone "us-east1-b"
   :workerMachineType "n1-standard-1"})

(defn apply-transformations-to-pipeline
 [read-subscription outputTable pipeline]
 (->> pipeline

      ;; Read the messages from PubSub
      (ps/read-from-pubsub read-subscription {:name "read-interactions-from-pubsub"})

      ; ;; Transform to a BigQuery Row

      ; (ds/map (fn [message]
      ;           (do
      ;            (log/info (str "Got message:\n" message))))
      ;         {:name "log-message"})

      ;
      (ds/map (fn [{:keys [sender referenceNumber userId requestId date interactionId type payload user __key__ __error__ __has_error__]}]
                  {:sender "test"
                   :referenceNumber "domtest123"
                   :userId "dom@test.com"
                   :requestId "long uuid"
                   :date "date"
                   :interactionId "notherlonguuid"
                   :type "testType"
                   :payload "{'stuff':'in a record'}"
                   :user "{'stuff':'in a record'}"
                   :__key__ "{'stuff':'in a record'}"
                   :__error__ "EhROAR"
                   :__has_error__ false})
             {:name "create-BQ-row"})

      ; Write the Row to BigQuery

      (bq/write-bq-table outputTable {:schema [{:name "sender" :type "STRING"}
                                               {:name "referenceNumber" :type "STRING"}
                                               {:name "userId" :type "STRING"}
                                               {:name "requestId" :type "STRING"}
                                               {:name "date" :type "STRING"}
                                               {:name "interactionId" :type "STRING"}
                                               {:name "type" :type "STRING"}
                                               {:name "payload" :type "RECORD"}
                                               {:name "user" :type "RECORD"}
                                               {:name "__key__" :type "RECORD"}
                                               {:name "__error__" :type "STRING"}
                                               {:name "__has_error__" :type "BOOLEAN"}]
                                      :name "write-to-bigquery"
                                      :create-disposition :if-needed
                                      :write-disposition :append})))

(defn -main
  [& args]
  (let [pipeline (ds/make-pipeline
                  DataflowPipelineOptions
                  []
                  pipeline-options)
        {:keys [project]} (ds/get-pipeline-configuration pipeline)
        read-subscription (format "projects/%s/subscriptions/dataflow-events" project)
        outputTable "simply-pre-prod:Events.all_events"]
    (->> pipeline
         (apply-transformations-to-pipeline read-subscription outputTable)
         (ds/run-pipeline))))
```

**Comment by MartinSahlen** [comment]
Just glancing your code and error message I see you are not deserializing the pubsub message to a map, and then the json parser in the pubsub writer complains because it needs a map and get a string as the message says. Looking at https://cloud.google.com/dataflow/model/pubsub-io I Indeed see that pubsub gives you a string that you need to parse to a map. Something like this: `  (json/parse-string pubsub-message` keyword))

**Comment by domparry** [comment]
Ah. Reading the docs a bit more, I see there is a json coder that can be used in the pubsub read step. I was just following the example code...  Sorry to make you debug my code! Thanks for the steer.

**Comment by domparry** [comment]
Just to close this off. Huge thanks again for pointing me in the right direction. For others who find thread, here's how to deal with cases where you're reading a JSON document from pubsub:

include the following import:

`[com.google.cloud.dataflow.sdk.coders TableRowJsonCoder]`

and then add the coder to your transform like this:

```
      (ps/read-from-pubsub read-subscription {:name "read-interactions-from-pubsub"
                                              :coder (TableRowJsonCoder/of)})
```

**Comment by MartinSahlen** [comment]
Great to hear you are back on track. I would however consider using clojure's json parser as suggested - how would it work to do data transforms in clojure with the output from `TableRowJsonCoder`? Does it give you a clojure map? Since it's a java class I would assume not. Just giving a heads up that it might give you issues if trying to work with the data in native clojure in a more advanced pipeline than the one you are testing now.

I also wonder if it affects performance in any way to use clojure's json parser instead of the one you are using.

**Comment by domparry** [comment]
You're correct, it's not a clojure data structure. You get back a TableRow, which you then convert to a clojure map with bq/table-row->clj. Then you have clojure magic all the way till you need to write it back. Then you use: bq/clj-nested->table-row, which gives you back the TableRow.

**Comment by MartinSahlen** [comment]
Just a pro tip: You dont really need to parse this back and forth, the `bq/write-bq-table` handles exactly this for you if you check the source: https://github.com/ngrunwald/datasplash/blob/master/src/datasplash/bq.clj#L182

**Comment by domparry** [comment]
Trying to do what you suggested here, but I'm back to:

 `unable to deserialize datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn`

I'm using the pubsub example, and calling my function the same way (using ds/map), because the thing you get back from read-from-pubsub is wrapped in a PCollection.

Here is the code, because for the life of me I can't figure out why (I have tested parse-and-clean-names separately with the same JSON payload, which I've pulled off pubsub as a test):

```
(defn parse-and-clean-names
  [s]
  (json/parse-string s (fn [k] (keyword (str/replace k #"-" "_")))))


(defn apply-transformations-to-pipeline
 [read-subscription outputTable pipeline]

 (->> pipeline

      (ps/read-from-pubsub read-subscription {:name "read-interactions-from-pubsub"})

      (ds/map parse-and-clean-names {:name "read-interactions-from-pubsub"})

............<snip>...........
```

Which is called by:

```
(defn -main
  [& args]
  (let [pipeline (ds/make-pipeline
                  DataflowPipelineOptions
                  []
                  pipeline-options)
        {:keys [project]} (ds/get-pipeline-configuration pipeline)
        read-subscription (format "projects/%s/subscriptions/dataflow-events" project)
        outputTable "simply-pre-prod:Events.all_events"]
    (->> pipeline
         (apply-transformations-to-pipeline read-subscription outputTable)
         (ds/run-pipeline))))
```

I get this stacktrace:

```
lein run
Feb 21, 2017 8:07:54 AM com.google.cloud.dataflow.sdk.runners.DataflowPipelineRunner fromOptions
INFO: PipelineOptions.filesToStage was not specified. Defaulting to files from the classpath: will stage 88 files. Enable logging at DEBUG level to see which files will be staged.
Exception in thread "main" java.lang.IllegalArgumentException: unable to deserialize datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn$ff19274a@4bf8b77, compiling:(/private/var/folders/mc/6vrbpxbs60q4hwdrp8wm89380000gn/T/form-init936263165647874268.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: unable to deserialize datasplash.core.proxy$com.google.cloud.dataflow.sdk.transforms.DoFn$ff19274a@4bf8b77
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:76)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.clone(SerializableUtils.java:91)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Bound.<init>(ParDo.java:720)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Unbound.of(ParDo.java:678)
	at com.google.cloud.dataflow.sdk.transforms.ParDo$Unbound.access$000(ParDo.java:596)
	at com.google.cloud.dataflow.sdk.transforms.ParDo.of(ParDo.java:563)
	at com.google.cloud.dataflow.sdk.transforms.ParDo.of(ParDo.java:558)
	at datasplash.core$map_op$make_map_op__5352.invoke(core.clj:500)
	at fulliautomatix.core$apply_transformations_to_pipeline.invokeStatic(core.clj:45)
	at fulliautomatix.core$apply_transformations_to_pipeline.invoke(core.clj:37)
	at fulliautomatix.core$_main.invokeStatic(core.clj:79)
	at fulliautomatix.core$_main.doInvoke(core.clj:69)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init936263165647874268.clj:1)
	at user$eval5.invoke(form-init936263165647874268.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Caused by: java.lang.ClassNotFoundException: fulliautomatix.core$parse_and_clean_names
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1714)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at com.google.cloud.dataflow.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:73)
	... 32 more
```

This ```Caused by: java.lang.ClassNotFoundException: fulliautomatix.core$parse_and_clean_names``` is because I don't have a version of parse-and-clean-names that handles ByteArray (I think). A little lost here again, but I feel like I'm following the example exactly, but doing something stupid somewhere...

**Comment by domparry** [comment]
So... Just to close this off again. I, am an idiot. I read somewhere, that this exception is because I'm trying to use an anonymous function, but it didn't make sense because it had a name. But, this:

`java.lang.ClassNotFoundException: fulliautomatix.core$parse_and_clean_names`

should have SCREAMED out to me. This was missing:

`(compile 'fulliautomatix.core)`

Thanks again for all the help.
