### ISSUE TITLE
No matching method found: withNumQuerySplit for class com.google.cloud.dataflow.sdk.io.datastore.DatastoreV1$Read

### ISSUE THREAD

**Issue by domparry** [ngrunwald/datasplash#23]
Hi there,

Seems to be a typo in read-datastore-raw when passing in option :num-query-split. When invoking like this:

```
(dts/read-datastore-raw {:name "Read Events from Datastore"
                                             :project-id dataset
                                             :query (make-event-query interactionId)
                                             :namespace namespace
                                             :num-query-split 1})
```

I got the following exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: No matching method found: withNumQuerySplit for class com.google.cloud.dataflow.sdk.io.datastore.DatastoreV1$Read, compiling:(/private/var/folders/mc/6vrbpxbs60q4hwdrp8wm89380000gn/T/form-init7020878441071113286.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No matching method found: withNumQuerySplit for class com.google.cloud.dataflow.sdk.io.datastore.DatastoreV1$Read
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:53)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at datasplash.datastore$read_datastore_raw.invokeStatic(datastore.clj:30)
	at datasplash.datastore$read_datastore_raw.invoke(datastore.clj:21)
	at fulliautomatix.fix_events$fetch_and_fix_events.invokeStatic(fix_events.clj:65)
	at fulliautomatix.fix_events$fetch_and_fix_events.invoke(fix_events.clj:59)
	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
	at clojure.core$map$fn__4785.invoke(core.clj:2644)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$map$fn__4785.invoke(core.clj:2637)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3024)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at clojure.core$doall.invoke(core.clj:3039)
	at fulliautomatix.fix_events$apply_transformations_to_pipeline.invokeStatic(fix_events.clj:90)
	at fulliautomatix.fix_events$apply_transformations_to_pipeline.invoke(fix_events.clj:86)
	at fulliautomatix.fix_events$run_main.invokeStatic(fix_events.clj:102)
	at fulliautomatix.fix_events$run_main.invoke(fix_events.clj:93)
	at fulliautomatix.core$run_fix_events.invokeStatic(core.clj:15)
	at fulliautomatix.core$run_fix_events.invoke(core.clj:13)
	at fulliautomatix.core$_main.invokeStatic(core.clj:32)
	at fulliautomatix.core$_main.doInvoke(core.clj:26)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at clojure.lang.Var.invoke(Var.java:388)
	at user$eval5.invokeStatic(form-init7020878441071113286.clj:1)
	at user$eval5.invoke(form-init7020878441071113286.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
```

Looking at the documentation, I think the method to be called is: `withNumQuerySplits` <- note the "s" at the end.

I'll submit a PR to fix this.

**Comment by domparry** [comment]
PR submitted, but on the uncast fork as I'm working off that base due to a bug in the last merge....

**Comment by domparry** [comment]
Re-opened until PR is merged.

**Comment by torbjornvatn** [comment]
@domparry maybe you could submit your PR here based on the new 0.5.0 version?

**Comment by domparry** [comment]
Good point. I'll see if this is still a problem in the 0.5 codebase.
