### ISSUE TITLE
clojure.lang.ExceptionInfo: Unfreezable type: class com.google.cloud.dataflow.sdk.repackaged.com.google.common.collect.Iterables$

### ISSUE THREAD

**Issue by domparry** [ngrunwald/datasplash#26]
Hi there,

I have some strange behaviour, and I'm wondering if anyone has run into this or can see something obvious...

I have a pipeline that runs 100%, pulling the same dataset using `InProcessPipelineRunner`, but when I push to `DataflowPipelineRunner` I get the exception below. It seems nippy is not able to serialize the data when running in the cloud, but does so perfectly locally. This is in a using a combin call with the following:

```
answer-data     (->> pipeline
                             (fetch-kind :Sales :answer)
                             (ds/map transform-answers {:name "transform-and-add-key"})
                             (ds/map-kv (fn [{:keys [interactionId answers]}]
                                          [interactionId answers]))
                             (ds/combine
                              (ds/sfn (fn [answers] answers))
                              {:scope :per-key})
                             (ds/map (fn [[interactionId answers]]
                                       {:interactionId interactionId
                                        :answers (vec answers)}))
```

I've successfully run the code and checkout the output up to the point past the map-kv, and the correct output is given for all the data.

```
2017-08-06T19:23:04.010Z: Error:   (e60b7ed2b9fb314e): java.lang.RuntimeException: java.lang.IllegalArgumentException: Unable to encode element '[[{:questionId "age", :answer "28"}, {:questionId "gender", :answer "Female"}, {:questionId "income", :answer "4000"}, {:questionId "smoker", :answer "No"}]]' with coder 'CustomCoder$ff19274a'.
	at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:160)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:288)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:284)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnProcessContext$1.outputWindowedValue(DoFnRunnerBase.java:508)
	at com.google.cloud.dataflow.sdk.util.GroupAlsoByWindowsAndCombineDoFn.closeWindow(GroupAlsoByWindowsAndCombineDoFn.java:203)
	at com.google.cloud.dataflow.sdk.util.GroupAlsoByWindowsAndCombineDoFn.processElement(GroupAlsoByWindowsAndCombineDoFn.java:190)
	at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:49)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:139)
	at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:188)
	at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47)
	at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55)
	at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:221)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.start(ReadOperation.java:182)
	at com.google.cloud.dataflow.sdk.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:69)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.executeWork(DataflowWorker.java:285)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.doWork(DataflowWorker.java:221)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:171)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:192)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:172)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:159)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unable to encode element '[[{:questionId "age", :answer "28"}, {:questionId "gender", :answer "Female"}, {:questionId "income", :answer "4000"}, {:questionId "smoker", :answer "No"}]]' with coder 'CustomCoder$ff19274a'.
	at com.google.cloud.dataflow.sdk.coders.StandardCoder.getEncodedElementByteSize(StandardCoder.java:170)
	at datasplash.core.proxy$com.google.cloud.dataflow.sdk.coders.CustomCoder$ff19274a.getEncodedElementByteSize(Unknown Source)
	at com.google.cloud.dataflow.sdk.coders.StandardCoder.registerByteSizeObserver(StandardCoder.java:185)
	at datasplash.core.proxy$com.google.cloud.dataflow.sdk.coders.CustomCoder$ff19274a.registerByteSizeObserver(Unknown Source)
	at com.google.cloud.dataflow.sdk.coders.IterableLikeCoder.registerByteSizeObserver(IterableLikeCoder.java:211)
	at com.google.cloud.dataflow.sdk.coders.IterableLikeCoder.registerByteSizeObserver(IterableLikeCoder.java:60)
	at com.google.cloud.dataflow.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:158)
	at com.google.cloud.dataflow.sdk.coders.KvCoder.registerByteSizeObserver(KvCoder.java:42)
	at com.google.cloud.dataflow.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:641)
	at com.google.cloud.dataflow.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:552)
	at com.google.cloud.dataflow.sdk.runners.worker.MapTaskExecutorFactory$ElementByteSizeObservableCoder.registerByteSizeObserver(MapTaskExecutorFactory.java:351)
	at com.google.cloud.dataflow.sdk.util.common.worker.OutputObjectAndByteCounter.update(OutputObjectAndByteCounter.java:125)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowOutputCounter.update(DataflowOutputCounter.java:61)
	at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:46)
	at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:158)
	... 25 more
Caused by: clojure.lang.ExceptionInfo: Unfreezable type: class com.google.cloud.dataflow.sdk.repackaged.com.google.common.collect.Iterables$2 {:type com.google.cloud.dataflow.sdk.repackaged.com.google.common.collect.Iterables$2, :as-str "#object[com.google.cloud.dataflow.sdk.repackaged.com.google.common.collect.Iterables$2 0x69e1dde3 \"[[{:questionId \\\"age\\\", :answer \\\"28\\\"}, {:questionId \\\"gender\\\", :answer \\\"Female\\\"}, {:questionId \\\"income\\\", :answer \\\"4000\\\"}, {:questionId \\\"smoker\\\", :answer \\\"No\\\"}]]\"]"}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at taoensso.nippy$throw_unfreezable.invokeStatic(nippy.clj:720)
	at taoensso.nippy$throw_unfreezable.invoke(nippy.clj:718)
	at taoensso.nippy$fn__4162.invokeStatic(nippy.clj:924)
	at taoensso.nippy$fn__4162.invoke(nippy.clj:905)
	at taoensso.nippy$fn__3965$G__3960__3972.invoke(nippy.clj:314)
	at taoensso.nippy$fn__4000.invokeStatic(nippy.clj:331)
	at taoensso.nippy$fn__4000.invoke(nippy.clj:316)
	at taoensso.nippy$fn__3983$G__3978__3990.invoke(nippy.clj:315)
	at taoensso.nippy$freeze_to_out_BANG_.invokeStatic(nippy.clj:728)
	at taoensso.nippy$freeze_to_out_BANG_.invoke(nippy.clj:725)
	at datasplash.core$make_nippy_coder$fn__5385.invoke(core.clj:365)
	at datasplash.core.proxy$com.google.cloud.dataflow.sdk.coders.CustomCoder$ff19274a.encode(Unknown Source)
	at com.google.cloud.dataflow.sdk.coders.StandardCoder.getEncodedElementByteSize(StandardCoder.java:167)
	... 39 more```

**Comment by domparry** [comment]
I fixed this. I moved the `vec` into the combine, as it was trying to return a java vector which nippy seems to handle for `InProcessDataflowPipeline`, and for some reason not in `DataflowPipelineRunner`. Here is the fixed code:

```
answer-data     (->> pipeline
                             (fetch-kind :Sales :answer)
                             (ds/map transform-answers {:name "transform-and-add-key"})
                             (ds/map-kv (fn [{:keys [interactionId answers]}]
                                          [interactionId answers]))
                             (ds/combine
                              (ds/sfn (fn answer-combine-fn [answers]
                                        (vec answers)))
                              {:scope :per-key})                             
                             (ds/map (fn [[interactionId answers]]
                                       {:interactionId interactionId
                                        :answers answers})))     
```
